#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boot
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ManageCoreCompetency")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertrelation1(relation1 instance);
    partial void Updaterelation1(relation1 instance);
    partial void Deleterelation1(relation1 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ManageCoreCompetencyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_CoreCompetency> TB_CoreCompetency
		{
			get
			{
				return this.GetTable<TB_CoreCompetency>();
			}
		}
		
		public System.Data.Linq.Table<relation1> relation1
		{
			get
			{
				return this.GetTable<relation1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CoreCompetency")]
	public partial class TB_CoreCompetency
	{
		
		private int _ID;
		
		private string _CoreCompetency;
		
		private string _Specialty;
		
		private string _Version;
		
		public TB_CoreCompetency()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoreCompetency", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string CoreCompetency
		{
			get
			{
				return this._CoreCompetency;
			}
			set
			{
				if ((this._CoreCompetency != value))
				{
					this._CoreCompetency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specialty", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string Specialty
		{
			get
			{
				return this._Specialty;
			}
			set
			{
				if ((this._Specialty != value))
				{
					this._Specialty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NChar(25)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.relation1")]
	public partial class relation1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _课程;
		
		private string _运用数学_科学及工程知识的能力;
		
		private string _设计与执行实验_以及分析与解释数据的能力;
		
		private string _执行工程实务所需的技术_技巧及使用现代工具的能力;
		
		private string _设计工程系统_组件或制程的能力;
		
		private string _专案管理_含经费规划__有效沟通_领域整合与团队合作的能力;
		
		private string _发掘_分析_应用研究成果及因应复杂且整合性工程的能力;
		
		private string _认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力;
		
		private string _理解及应用专业伦理_认知社会责任及尊重多元观点;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On课程Changing(string value);
    partial void On课程Changed();
    partial void On运用数学_科学及工程知识的能力Changing(string value);
    partial void On运用数学_科学及工程知识的能力Changed();
    partial void On设计与执行实验_以及分析与解释数据的能力Changing(string value);
    partial void On设计与执行实验_以及分析与解释数据的能力Changed();
    partial void On执行工程实务所需的技术_技巧及使用现代工具的能力Changing(string value);
    partial void On执行工程实务所需的技术_技巧及使用现代工具的能力Changed();
    partial void On设计工程系统_组件或制程的能力Changing(string value);
    partial void On设计工程系统_组件或制程的能力Changed();
    partial void On专案管理_含经费规划__有效沟通_领域整合与团队合作的能力Changing(string value);
    partial void On专案管理_含经费规划__有效沟通_领域整合与团队合作的能力Changed();
    partial void On发掘_分析_应用研究成果及因应复杂且整合性工程的能力Changing(string value);
    partial void On发掘_分析_应用研究成果及因应复杂且整合性工程的能力Changed();
    partial void On认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力Changing(string value);
    partial void On认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力Changed();
    partial void On理解及应用专业伦理_认知社会责任及尊重多元观点Changing(string value);
    partial void On理解及应用专业伦理_认知社会责任及尊重多元观点Changed();
    #endregion
		
		public relation1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_课程", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 课程
		{
			get
			{
				return this._课程;
			}
			set
			{
				if ((this._课程 != value))
				{
					this.On课程Changing(value);
					this.SendPropertyChanging();
					this._课程 = value;
					this.SendPropertyChanged("课程");
					this.On课程Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[运用数学、科学及工程知识的能力]", Storage="_运用数学_科学及工程知识的能力", DbType="NChar(10)")]
		public string 运用数学_科学及工程知识的能力
		{
			get
			{
				return this._运用数学_科学及工程知识的能力;
			}
			set
			{
				if ((this._运用数学_科学及工程知识的能力 != value))
				{
					this.On运用数学_科学及工程知识的能力Changing(value);
					this.SendPropertyChanging();
					this._运用数学_科学及工程知识的能力 = value;
					this.SendPropertyChanged("运用数学_科学及工程知识的能力");
					this.On运用数学_科学及工程知识的能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[设计与执行实验，以及分析与解释数据的能力]", Storage="_设计与执行实验_以及分析与解释数据的能力", DbType="NChar(10)")]
		public string 设计与执行实验_以及分析与解释数据的能力
		{
			get
			{
				return this._设计与执行实验_以及分析与解释数据的能力;
			}
			set
			{
				if ((this._设计与执行实验_以及分析与解释数据的能力 != value))
				{
					this.On设计与执行实验_以及分析与解释数据的能力Changing(value);
					this.SendPropertyChanging();
					this._设计与执行实验_以及分析与解释数据的能力 = value;
					this.SendPropertyChanged("设计与执行实验_以及分析与解释数据的能力");
					this.On设计与执行实验_以及分析与解释数据的能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[执行工程实务所需的技术、技巧及使用现代工具的能力]", Storage="_执行工程实务所需的技术_技巧及使用现代工具的能力", DbType="NChar(10)")]
		public string 执行工程实务所需的技术_技巧及使用现代工具的能力
		{
			get
			{
				return this._执行工程实务所需的技术_技巧及使用现代工具的能力;
			}
			set
			{
				if ((this._执行工程实务所需的技术_技巧及使用现代工具的能力 != value))
				{
					this.On执行工程实务所需的技术_技巧及使用现代工具的能力Changing(value);
					this.SendPropertyChanging();
					this._执行工程实务所需的技术_技巧及使用现代工具的能力 = value;
					this.SendPropertyChanged("执行工程实务所需的技术_技巧及使用现代工具的能力");
					this.On执行工程实务所需的技术_技巧及使用现代工具的能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[设计工程系统、组件或制程的能力]", Storage="_设计工程系统_组件或制程的能力", DbType="NChar(10)")]
		public string 设计工程系统_组件或制程的能力
		{
			get
			{
				return this._设计工程系统_组件或制程的能力;
			}
			set
			{
				if ((this._设计工程系统_组件或制程的能力 != value))
				{
					this.On设计工程系统_组件或制程的能力Changing(value);
					this.SendPropertyChanging();
					this._设计工程系统_组件或制程的能力 = value;
					this.SendPropertyChanged("设计工程系统_组件或制程的能力");
					this.On设计工程系统_组件或制程的能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[专案管理(含经费规划)、有效沟通、领域整合与团队合作的能力]", Storage="_专案管理_含经费规划__有效沟通_领域整合与团队合作的能力", DbType="NChar(10)")]
		public string 专案管理_含经费规划__有效沟通_领域整合与团队合作的能力
		{
			get
			{
				return this._专案管理_含经费规划__有效沟通_领域整合与团队合作的能力;
			}
			set
			{
				if ((this._专案管理_含经费规划__有效沟通_领域整合与团队合作的能力 != value))
				{
					this.On专案管理_含经费规划__有效沟通_领域整合与团队合作的能力Changing(value);
					this.SendPropertyChanging();
					this._专案管理_含经费规划__有效沟通_领域整合与团队合作的能力 = value;
					this.SendPropertyChanged("专案管理_含经费规划__有效沟通_领域整合与团队合作的能力");
					this.On专案管理_含经费规划__有效沟通_领域整合与团队合作的能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[发掘、分析、应用研究成果及因应复杂且整合性工程的能力]", Storage="_发掘_分析_应用研究成果及因应复杂且整合性工程的能力", DbType="NChar(10)")]
		public string 发掘_分析_应用研究成果及因应复杂且整合性工程的能力
		{
			get
			{
				return this._发掘_分析_应用研究成果及因应复杂且整合性工程的能力;
			}
			set
			{
				if ((this._发掘_分析_应用研究成果及因应复杂且整合性工程的能力 != value))
				{
					this.On发掘_分析_应用研究成果及因应复杂且整合性工程的能力Changing(value);
					this.SendPropertyChanging();
					this._发掘_分析_应用研究成果及因应复杂且整合性工程的能力 = value;
					this.SendPropertyChanged("发掘_分析_应用研究成果及因应复杂且整合性工程的能力");
					this.On发掘_分析_应用研究成果及因应复杂且整合性工程的能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[认识时事议题，了解工程技术对环境、社会及全球的影响，并培养持续学习习惯与能力]", Storage="_认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力", DbType="NChar(10)")]
		public string 认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力
		{
			get
			{
				return this._认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力;
			}
			set
			{
				if ((this._认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力 != value))
				{
					this.On认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力Changing(value);
					this.SendPropertyChanging();
					this._认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力 = value;
					this.SendPropertyChanged("认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力");
					this.On认识时事议题_了解工程技术对环境_社会及全球的影响_并培养持续学习习惯与能力Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[理解及应用专业伦理，认知社会责任及尊重多元观点]", Storage="_理解及应用专业伦理_认知社会责任及尊重多元观点", DbType="NChar(10)")]
		public string 理解及应用专业伦理_认知社会责任及尊重多元观点
		{
			get
			{
				return this._理解及应用专业伦理_认知社会责任及尊重多元观点;
			}
			set
			{
				if ((this._理解及应用专业伦理_认知社会责任及尊重多元观点 != value))
				{
					this.On理解及应用专业伦理_认知社会责任及尊重多元观点Changing(value);
					this.SendPropertyChanging();
					this._理解及应用专业伦理_认知社会责任及尊重多元观点 = value;
					this.SendPropertyChanged("理解及应用专业伦理_认知社会责任及尊重多元观点");
					this.On理解及应用专业伦理_认知社会责任及尊重多元观点Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
